# Generated by Django 3.0.3 on 2020-02-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apllicant',
            new_name='Applicant',
        ),
    ]
