# Generated by Django 3.0.3 on 2020-02-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200209_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_at',)},
        ),
    ]
